name: test-task

tags:
  - name: 简称
    label: 简称
    theme:
      background: '#91d5ff'

  - name: 人名
    label: 人名
    shortcut: '1'
    abbr: PERSON
    theme:
      background: '#97b6e2'

  - name: 地名
    label: 地名
    shortcut: '2'
    abbr: LOC
    theme:
      background: '#2196f3'

  - name: 货币
    label: 货币
    shortcut: '3'
    abbr: ￥
    theme:
      background: '#d379e8'

  - name: 日期
    label: 日期
    abbr: DATE
    shortcut: '4'
    theme:
      background: 'linear-gradient(rgb(230, 169, 169), #ff3030 70%, rgb(189, 125, 127))'

  - name: 时间
    label: 时间
    abbr: TIME
    shortcut: '5'
    theme:
      background: 'linear-gradient(rgb(239, 225, 183), rgb(255, 160, 19) 70%, rgb(156, 124, 64))'

  - name: 百分比
    label: 百分比
    abbr: PERC
    shortcut: '6'
    theme:
      background: 'linear-gradient(rgb(223, 243, 201), rgb(78, 202, 78) 70%, rgb(122, 177, 124))'

  - name: 机构名
    label: 机构名
    abbr: ORG
    shortcut: '7'
    theme:
      background: '#9cd5ff'

  - group: 机构名
    name: 公司
    label: 公司
    abbr: '[公司]'
    theme:
      background: '#a1be8a'

  - group: 机构名
    name: 事务所
    label: 事务所
    abbr: '[事务所]'
    theme:
      background: '#a1be8a'

  - group: 机构名
    name: 交易所
    label: 交易所
    abbr: '[交易所]'
    theme:
      background: '#a1be8a'

  - group: 机构名
    name: 银行
    label: 银行
    abbr: '[银行]'
    theme:
      background: '#a1be8a'

  - group: 机构名
    name: 学校
    label: 学校
    abbr: '[学校]'
    theme:
      background: '#a1be8a'

  - group: 机构名
    name: 金融投资机构
    label: 金融投资机构
    abbr: '[金融投资机构]'
    theme:
      background: '#a1be8a'

  - group: 机构名
    name: 政府机构部门
    label: 政府机构部门
    abbr: '[政府机构部门]'
    theme:
      background: '#a1be8a'

  - group: 其他
    name: 非货币数量词
    label: 非货币数量词
    abbr: '[非货币数量词]'
    theme:
      background: '#bdbdbd'

  - group: 其他
    name: 行业
    label: 行业
    abbr: '[行业]'
    theme:
      background: '#bdbdbd'

  - group: 其他
    name: 产品
    label: 产品
    abbr: '[产品]'
    theme:
      background: '#bdbdbd'
  - group: 其他
    name: 专利
    label: 专利
    abbr: '[专利]'
    theme:
      background: '#bdbdbd'
  - group: 其他
    name: 股票
    label: 股票
    abbr: '[股票]'
    theme:
      background: '#bdbdbd'
  - group: 其他
    name: 债券
    label: 债券
    abbr: '[债券]'
    theme:
      background: '#bdbdbd'
  - group: 其他
    name: 期货
    label: 期货
    abbr: '[期货]'
    theme:
      background: '#bdbdbd'
