name: test-task

tags:
  - name: 人名
    label: 人名
    shortcut: '1'
    abbr: PERSON
    theme:
      background: '#97b6e2'

  - name: 地名
    label: 地名
    shortcut: '2'
    abbr: LOC
    theme:
      background: '#aaaaaa'

  - name: 货币
    label: 货币
    shortcut: '3'
    abbr: ￥
    theme:
      background: '#d379e8'

  - name: 日期
    label: 日期
    abbr: DTAE
    shortcut: '4'
    theme:
      background: 'linear-gradient(rgb(230, 169, 169), #ff3030 70%, rgb(189, 125, 127))'

  - name: 时间
    label: 时间
    abbr: TIME
    shortcut: '5'
    theme:
      background: 'linear-gradient(rgb(239, 225, 183), rgb(255, 160, 19) 70%, rgb(156, 124, 64))'

  - name: 百分比
    label: 百分比
    abbr: PERCENTAGE
    shortcut: '6'
    theme:
      background: 'linear-gradient(rgb(223, 243, 201), rgb(78, 202, 78) 70%, rgb(122, 177, 124))'

  - name: 其他
    label: 其他
    abbr: OTHER
    shortcut: '7'
    theme:
      outline: '1px solid #ccc'

  - group: 机构名
    name: 公司
    label: 公司
    theme:
      background: '#f7a444'

  - group: 机构名
    name: 事务所
    label: 事务所
    theme:
      background: '#a1be8a'

  - group: 机构名
    name: 交易所
    label: 交易所
    theme:
      background: '#dddddd'

  - group: 机构名
    name: 银行
    label: 银行
    theme:
      background: '#f37ca5'

  - group: 机构名
    name: 学校
    label: 学校
    theme:
      background: '#a4e8d2'

  - group: 机构名
    name: 金融投资机构
    label: 政府机构部门
    theme:
      background: '#50b8c8'

