name: test-task

tags:
  - name: corporation
    label: 公司
    shortcut: '1'
    abbr: CORP
    theme:
      background: '#97b6e2'

  - name: person
    label: 人物
    shortcut: '2'
    abbr: PERSON
    theme:
      background: '#aaaaaa'

  - name: location
    label: 地点
    shortcut: '3'
    abbr: LOC
    theme:
      background: '#f7a444'

  - name: time
    label: 时间
    shortcut: '4'
    abbr: TIME
    theme:
      background: '#a1be8a'

  - name: sentence
    label: 句子
    group: 关系
    theme:
      background: '#dddddd'

  - name: modifier
    label: 修饰成分
    group: 关系
    theme:
      background: '#f37ca5'

  - name: subject
    label: 主语
    group: 关系
    abbr: S
    theme:
      background: '#a4e8d2'

  - name: predicate
    label: 谓语
    group: 关系
    abbr: P
    theme:
      background: '#50b8c8'

  - name: object
    label: 宾语
    group: 关系
    abbr: O
    theme:
      background: '#d379e8'

  - name: positive
    label: 正向
    group: 情感
    theme:
      background: 'linear-gradient(rgb(230, 169, 169), #ff3030 70%, rgb(189, 125, 127))'

  - name: neutral
    label: 中性
    group: 情感
    theme:
      background: 'linear-gradient(rgb(239, 225, 183), rgb(255, 160, 19) 70%, rgb(156, 124, 64))'

  - name: negative
    label: 负向
    group: 情感
    theme:
      background: 'linear-gradient(rgb(223, 243, 201), rgb(78, 202, 78) 70%, rgb(122, 177, 124))'

