name: test-task

tags:
  -
    name: corporation
    label: 公司
    shortcut: '1'
    category: primary
    abbr: CORP
    theme:
      backgroundColor: '#97b6e2'

  -
    name: nation
    label: 国家
    shortcut: '2'
    category: primary
    abbr: NATION
    theme:
      backgroundColor: '#f7a444'

  -
    name: time
    label: 时间
    shortcut: '3'
    category: primary
    abbr: TIME
    theme:
      backgroundColor: '#a1be8a'

  -
    name: concept
    label: 概念
    shortcut: '4'
    category: primary
    abbr: CPT
    theme:
      backgroundColor: '#d379e8'

  -
    name: sentence
    label: 句子
    shortcut: '5'
    category: primary
    abbr: SENT
    theme:
      backgroundColor: '#dddddd'

  -
    name: organization
    label: 组织
    shortcut: null
    category: secondary
    abbr: ORG
    theme:
      backgroundColor: '#d8eae4'
