name: test-task

tags:
  - name: corporation
    label: 公司
    shortcut: '1'
    abbr: CORP
    theme:
      background: '#97b6e2'

  - name: person
    label: 人物
    shortcut: '2'
    abbr: PERSON
    theme:
      background: '#ff6f42'

  - name: location
    label: 地点
    shortcut: '3'
    abbr: LOC
    theme:
      background: '#f7a444'

  - name: time
    label: 时间
    shortcut: '4'
    abbr: TIME
    theme:
      background: '#a1be8a'

  - name: sentence
    label: 句子
    group: 关系
    theme:
      background: '#dddddd'

  - name: subject
    label: 主语
    group: 关系
    abbr: S
    theme:
      background: '#a4e8d2'

  - name: predicate
    label: 谓语
    group: 关系
    abbr: P
    theme:
      background: '#50b8c8'

  - name: object
    label: 宾语
    group: 关系
    abbr: O
    theme:
      background: '#d379e8'

  - name: nouns
    label: 名词
    group: 词性
    theme:
      outline: '1px solid steelblue'

  - name: adjective
    label: 形容词
    group: 词性
    theme:
      outline: '1px solid orange'

  - name: verb
    label: 动词
    group: 词性
    theme:
      outline: '1px solid #ea2000'
